In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
from matplotlib.patches import Polygon
import pingouin as pg

In [8]:
mean1 = 4
mean2 = 3.8
mean3 = 7

N = 30

stdev = 2

In [10]:
data1 = mean1 + np.random.randn(N)*stdev
data2 = mean2 + np.random.randn(N)*stdev
data3 = mean3 + np.random.randn(N)*stdev

datamat = np.vstack((data1,data2,data3)).T

df = pd.DataFrame(data=datamat,columns=['d1','d2','d3'])

df

          d1         d2         d3
0   1.643128   0.583420   6.177363
1   2.335465   6.376809   6.293689
2   9.495293   7.655296   9.142997
3   1.559953   5.647706   9.454596
4   3.696607   3.806552   8.418068
5   4.186995   2.325666   7.883469
6   3.212643   1.966401   7.503410
7   4.271924   3.515917   5.846043
8   0.529997   3.983080   7.379027
9   5.101867   2.641695   7.571820
10  3.927163   6.126251   6.269980
11  7.434739   5.807876   4.425975
12  2.999702   2.136855  10.329623
13  5.055381   4.651473   4.586726
14  6.952818   1.284391   8.147550
15  1.890951   4.631706   8.936726
16  3.623919   1.979073   8.110470
17  4.852637   5.200145  12.564164
18  2.300567   2.640458   8.790936
19  4.099518   6.072715   4.875491
20  3.266913   0.067796   7.362327
21  4.046292   2.564744  10.913444
22  1.161893   5.425895   9.346587
23 -1.289199   6.534354   4.810674
24  5.270448   0.245775  12.962688
25  4.011438  10.127403   7.390961
26  3.354435   4.794750   5.084860
27  3.649058   1.066211   6.225965
28  3.970574   5.760780   9.630164
29  3.571267   6.165196   7.454676